/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExampleImport } from './routes/example'
import { Route as IndexImport } from './routes/index'
import { Route as ImageSlugImport } from './routes/image/$slug'

// Create/Update Routes

const ExampleRoute = ExampleImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ImageSlugRoute = ImageSlugImport.update({
  id: '/image/$slug',
  path: '/image/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleImport
      parentRoute: typeof rootRoute
    }
    '/image/$slug': {
      id: '/image/$slug'
      path: '/image/$slug'
      fullPath: '/image/$slug'
      preLoaderRoute: typeof ImageSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/image/$slug': typeof ImageSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/image/$slug': typeof ImageSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/image/$slug': typeof ImageSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/example' | '/image/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example' | '/image/$slug'
  id: '__root__' | '/' | '/example' | '/image/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleRoute: typeof ExampleRoute
  ImageSlugRoute: typeof ImageSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleRoute: ExampleRoute,
  ImageSlugRoute: ImageSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/example",
        "/image/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/example": {
      "filePath": "example.tsx"
    },
    "/image/$slug": {
      "filePath": "image/$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
